{{- if .Values.eventServices.recurringTask.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo-app.recurring-task-service.fullname" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: recurring-task-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo-app.recurring-task-service.fullname" . }}
  minReplicas: {{ .Values.eventServices.recurringTask.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.eventServices.recurringTask.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.eventServices.recurringTask.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.eventServices.recurringTask.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.eventServices.recurringTask.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.eventServices.recurringTask.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}