# SDD: Implements Task ID: T005, T006
"""Data models for the todo application.

This module contains the Task entity and TaskStatus enum.
"""

from dataclasses import dataclass
from enum import Enum


class TaskStatus(Enum):
    """Enumeration of possible task states."""

    PENDING = "Pending"
    COMPLETED = "Completed"


@dataclass
class Task:
    """Represents a single todo task.

    Attributes:
        id: Unique integer identifier (auto-generated by TodoManager)
        title: Required string representing the task name
        description: Optional string providing additional details
        status: Current state of the task (Pending or Completed)
    """

    id: int
    title: str
    description: str
    status: TaskStatus
